
platform :ios, ‘9.0’

target 'Demo' do

pod 'Masonry'
pod ‘yoga', :path => './ReactComponent/node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => './ReactComponent/node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'BatchedBridge'
  ]
end

